### ISSUE TITLE
Inverted C-Stick on Gamecube

### ISSUE THREAD

**Issue by tanjo3** [KernelZechs/open-joystick-display#40] opened 2020-02-04 21:33 UTC
Not really sure why, but my C-Stick is inverted on the Gamecube. The control stick is fine, but flicking left on the physical C-Stick show right on the display and similarly for up-down. Is there a way to invert this so that my display is accurate? My base mapping is the Mayflash one. Thanks.

**Comment by KernelZechs** [comment] 2020-02-05 01:05
I need the following information from you as per the ticket template. However, I have tested my GC mayflash adapter and it works as intended. Make sure it is set to PC mode and not Wii/Switch mode as this causes problems.

## For Bug Reports
- Information and version about the operating system you are currently using:
  - For **Microsoft Windows** you can get this information by going to `Command Prompt` and using the `systeminfo` command.
  - For **MacOS** you can find this in your `Apple Menu` > `About`
  - For **Linux** you will need provide the following:
    - Which distro you are currently using?
    - Which version of the distro are you currently on?
    - Which kernel you are using?
    - What desktop environment are you using? (Please include details on the window server such as X11 or Wayland as well)
    - Are you using desktop compositing? (If you don't know, likely yes)
    - Determine if your system is currently up to date.
    - If you're a Gentoo/Arch/Manjaro/Slackware user, a list of installed packages and libraries is required for me to proceed. 
- A detailed description in list format on how to recreate the bug. (Don't hide it in a paragraph of text)
- Screenshots and Videos will speed up resolution time. If you can please, provide them.

**Comment by tanjo3** [comment] 2020-02-05 04:40
Sorry, my bad.  

I'm running OJD on Windows 10 Pro, OJD is version 2.7.1.   

I currently have my Gamecube controller plugged into a pdobq adapter which is set to PC mode. Moving the C-Stick up reports a value of 0.7 on axis 2 and shows the stick moving down on the display. Moving the C-Stick left reports a value of 0.7 on axis 5 and shows the stick moving right on the display. The control stick works correctly. I have tried different controllers, adapter ports, and USB ports for the adapter and observe the same in all cases.  

Video demonstration of phyiscal and display controllers: https://youtu.be/v_nM9ZqvpD4

**Comment by KernelZechs** [comment] 2020-02-05 05:01
@tanjo3 pdobq isn't the same as the Mayflash (though may be similar in chipset, but clearly not programming). However your fix is simple. Just invert the axis on your directionals and they should work correctly. Let me know if this helps you. Below is a screenshot of the Mayflash controls (Directional ID 1 is the one you want to modify)

![image](https://user-images.githubusercontent.com/46404303/73812334-715aa600-47aa-11ea-800e-066eee2e9545.png)

**Comment by KernelZechs** [comment] 2020-02-05 05:04
I deleted my original solution, however I stand by the issues with the pdobq being different from the mayflash.

Let me look at this and get back to you, I think there just needs to be an inverted option added to the directionals.

**Comment by KernelZechs** [comment] 2020-02-10 02:13
@tanjo3 2.8.0 is live. You will see an Invert X and Invert Y option for directionals now. This will allow you to tune this to your controller. You can download the latest packages here: https://ojdproject.com/

I'm going to close this ticket, please feel free to re-open if you have any more issues. Thanks.

**Closed by KernelZechs** 2020-02-10 02:13 UTC
Labels: help wanted
