### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by Paragoumba** [KernelZechs/open-joystick-display#48] opened 2020-04-01 12:45 UTC
I have by going on your website that you provide a portable archive of the project and that there is no open-joystick-display can be found on the AUR (Arch User Repositories). I think it would benefit some people (at least Arch based distribution users) to add OJD to the AUR. I will try to create one myself and update this issue afterwards.

**Comment by KernelZechs** [comment] 2020-04-01 12:53
That would be nice to have since I use Arch. However, keep in mind if you're going to maintain that aur reference to just work with me when I move things around. I would just use the general linux build and just unpack it in `/opt/open-joystick-display'. Thanks for letting me know!

**Comment by Paragoumba** [comment] 2020-04-01 20:47
I started creating the package but I've seen that the latest version on GitHub is the v2.7.1 but on the website the v2.8.0 is available. Since the AUR package will download the sources of the latest Release, it would be nice to create the v2.8.0 one on GitHub.
Furthermore, I couldn't find any instructions on how to compile from source. I think it is an important thing to add to the README and it will be mandatory for me to write the script so pacman can compile the package from source.

**Comment by KernelZechs** [comment] 2020-04-01 23:01
@Paragoumba I can update the tagging and add documentation to it this evening. I'll let you know when that is done.

**Comment by KernelZechs** [comment] 2020-04-02 02:09
@Paragoumba tagging has been fixed, you can follow the build guide here: https://github.com/KernelZechs/open-joystick-display/blob/master/BUILD.md

**Comment by Paragoumba** [comment] 2020-04-03 19:33
Perfect! I tried to compile and... couldn't make it work :/ After install yarn with `pacman -S yarn`, I ran `yarn install` and it failed with the following [stacktrace](https://pastebin.com/PfHmbEvw). Running `yarn build` worked surprisingly. All the builds are in the dist directory as expected. The built binary executes without error. Isn't there a way to build just the .tar.gz archive (or even just the linux-unpacked directory) as it's the only one used to make the package and that the AppImage takes a lot of time to be built?

**Comment by Paragoumba** [comment] 2020-04-03 19:49
I investigated a bit and it appears that a `npm install` worked and replaced the `yarn install` but when I launch the PKGBUILD it always fails at `npm install`

**Comment by KernelZechs** [comment] 2020-04-03 20:27
@Paragoumba don't use npm install as the application is designed around using yarn. To install yarn you should use `npm` and not `pacman` so `npm install --global yarn gulp` is what you should be doing, from there `yarn` is a global command and should work as intended.

In regards to reducing the build to the unpacked, I'll figure out a way you can do so.

**Comment by KernelZechs** [comment] 2020-04-03 20:32
@Paragoumba 

`gulp build && gulp rebuild-electron && yarn electron-builder --linux dir` 

Here is a command you can use instead of `yarn build`

**Comment by Paragoumba** [comment] 2020-04-03 21:01
Ok for now it works! linux-unpacked is built in 6s, that's really nice.

**Comment by Paragoumba** [comment] 2020-04-03 21:59
I pushed a first version on the AUR. The link is [https://aur.archlinux.org/packages/open-joystick-display](https://aur.archlinux.org/packages/open-joystick-display).

**Comment by Paragoumba** [comment] 2020-04-03 22:03
The CHANGELOG isn't used for now because makepkg expects it to be present before the source archive is downloaded but the one I want to use is in the archive. I'll have to fix that.

**Comment by KernelZechs** [comment] 2020-04-03 23:51
@Paragoumba awesome! A few things, I tried it out just to see and I'm getting this installer error

```
100   140  100   140    0     0    619      0 --:--:-- --:--:-- --:--:--   619
100 21.5M    0 21.5M    0     0  14.0M      0 --:--:--  0:00:01 --:--:-- 23.6M
==> Validating source files with sha256sums...
    open-joystick-display-2.8.0.tar.gz ... Passed
==> Making package: open-joystick-display 2.8.0-1 (Fri 03 Apr 2020 07:49:06 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found open-joystick-display-2.8.0.tar.gz
==> Validating source files with sha256sums...
    open-joystick-display-2.8.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting open-joystick-display-2.8.0.tar.gz with bsdtar
==> Starting prepare()...
Prepare /home/adragoni/.cache/yay/open-joystick-display/pkg/open-joystick-display /home/adragoni/.cache/yay/open-joystick-display/src
==> Sources are ready.
==> Making package: open-joystick-display 2.8.0-1 (Fri 03 Apr 2020 07:49:08 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
[19:49:08] Local modules not found in ~/.cache/yay/open-joystick-display/src/open-joystick-display-2.8.0
[19:49:08] Try running: npm install
==> ERROR: A failure occurred in build().
    Aborting...
Error making: open-joystick-display
```

Furthermore the license is actually a `BSD 4-Clause with Attribution`, an example of this can be found here: https://fedoraproject.org/wiki/Licensing/BSD_with_Attribution

**Comment by Paragoumba** [comment] 2020-04-04 16:49
Ok, I fixed some problems but now it doesn't compile anymore with [this stacktrace](https://pastebin.com/WAXRKB7G)

**Comment by KernelZechs** [comment] 2020-04-04 19:44
@Paragoumba `/home/paragoumba/.cache/node-gyp/13.12.0/` it's not using node 12 LTS (Latest: 12.16.1), it is using bleeding edge 13 (13.12.0) which isn't supported (this is in the guide).

At this point, I would skip building a binary and use the general linux binary I have on the website (it works in Arch/Manjaro/Gentoo/Fedora/Ubuntu/Mint/etc)  and pack it into the AUR repo as a (BIN) pack. Link: https://ojdproject.com/downloads/linux/stable/x64/open-joystick-display-2.8.0-x64-linux.tar.gz

If you're trying to make this repo multi-arch compatible (32-bit, arm, etc) then I regret to say  I don't support it. (I dropped 32-bit last year, and I don't know of any 'streamer ready' ARM boxes in existence, if that changes I'll cross-compile it when that happens).

This should help wrap this up.

**Comment by KernelZechs** [comment] 2020-04-05 02:40
@Paragoumba here is a working PKGBUILD with the binary in question. Give this a try and let me know. This also has a couple of other modifications:

- Correct License Type
- Remove of Prepare/Build (Not Required)
- Restricted arch to x86_64
- Bumped Package Rel to '2'
- Binary File Install

```
# Maintainer: Paragoumba <paragoumba at protonmail dot com>
pkgname=open-joystick-display
pkgver=2.8.0
pkgrel=2
pkgdesc="A powerful and easy to use streamer-ready overlay for your joystick or gamepad. Completely free and open source."
arch=("x86_64")
url="https://ojdproject.com/"
license=('custom:BSD 4-Clause With Attribution')
source=("$pkgname-$pkgver.tar.gz::https://ojdproject.com/downloads/linux/stable/x64/open-joystick-display-2.8.0-x64-linux.tar.gz")
sha256sums=('e821ff39a073fdb6237c139ba28855f1edfeb44d9a93edefcb423b1ee9d81515')

package() {
    install -Dm 644 ../"$pkgname".desktop -t "$pkgdir"/usr/share/applications/
    
    cd "$pkgname-$pkgver/"
    install -Dm 644 icons/icon.png "$pkgdir"/usr/share/pixmaps/open-joystick-display.png
    install -dm 755 "$pkgdir"/opt/open-joystick-display/    
    
    cp -r * "$pkgdir"/opt/open-joystick-display/

    mkdir -p "$pkgdir/usr/bin/"
    ln -s "/opt/$pkgname/$pkgname" "$pkgdir/usr/bin/$pkgname"
}
```

**Comment by KernelZechs** [comment] 2020-04-15 19:51
I'm closing this out since there hasn't been any progress. I do just suggest using the binary package since the current package up on AUR is broken and I'm bound to get support inquiries about it. If you have an update let me know in this ticket, otherwise remove the package from AUR or fix it would be my only plea for my support sanity.

Thanks.

**Closed by KernelZechs** 2020-04-15 19:51 UTC
Labels: enhancement

**Comment by Paragoumba** [comment] 2020-04-20 09:08
Sorry for being long to respond but I finally fixed the AUR package. I updated it on the AUR, I tested it and it should work now.
