### ISSUE TITLE
Support for Wheels?

### ISSUE THREAD

**Issue by leillo1975** [KernelZechs/open-joystick-display#26] opened 2019-12-18 11:39 UTC
Hello
I just discovered this software, and I really impressed. I would like to know if in future do you plan to give support to Steering Wheels. I think that a lot of simracer streamers would benefit from your software. As a Linux user I'm an user of a Logitech Wheel, that is the only wheel brand that gives a good support in our system.

**Comment by KernelZechs** [comment] 2019-12-18 14:15
Good Morning @leillo1975 

Someone asked me about this over in the obs forums awhile back about this feature, unfortunately I don't have any logitech wheels to do testing on otherwise I would add the feature. However, if you want to help out I can try and figure it out with your help.

Go to this site:
https://html5gamepad.com/

Hit a button on your wheel and then it should activate. Turn your wheel and record the results and send me a video of that website. 

From there I should be able to figure out how to engineer the feature. 

Thanks!

**Comment by leillo1975** [comment] 2019-12-18 15:10
> Hit a button on your wheel and then it should activate. Turn your wheel and record the results and send me a video of that website.

Do you want a video recording of the web Browser Screen (OBS), or a video of the wheel while I'm turning and pressing the buttons (using a mobile telephone or webcam)?

**Comment by berarma** [comment] 2019-12-18 15:18
Hi. I can send you the mappings for the G29 and its G27 emulation mode.

Notice below that the website shows the real device name but the device ID of the emulated device.

Also, the rotation range of these wheels can be configured from 40º to 900º. Thus, the same [-1,1] range may correspond to a wheel rotation of 40º to 900º depending on configuration.

Logitech G29 Driving Force:

```
046d-c24f-Logitech G29 Driving Force Racing Wheel

Wheel: Axis 0 (-1 full left, 1 full right)
Accelerator pedal: Axis 2 (1 released, -1 pressed)
Brake pedal: Axis 3 (1 released, -1 pressed)
Cluth pedal: Axis 1 (1 released, -1 pressed)
DPAD left/right: Axis 4 (-1 left, 1 right)
DPAD up/down: Axis 5 (-1 up, 1 down)
Button X: B0
Button Square: B1
Button Circle: B2
Button Triangle: B3
Right paddle shifter: B4
Left paddle shifter: B5
R2: B6
L2: B7
Share: B8
Option: B9
R3: B10
L3: B11
Shifter 1st gear: B12
Shifter 2nd gear: B13
Shifter 3rd gear: B14
Shifter 4th gear: B15
Shifter 5th gear: B16
Shifter 6th gear: B17
Shifter reverse gear: B18
Button "+": B19
Button "-": B20
Red knob right: B21
Red knob left: B22
Button Intro (inside red knob): B23
Button with Playstation logo: B24
```

Logitech G29 Driving Force in G27 emulation mode:

```
046d-c29b-Logitech G29 Driving Force Racing Wheel

Wheel: Axis 0 (-1 full left, 1 full right)
Accelerator pedal: Axis 2 (1 released, -1 pressed)
Brake pedal: Axis 3 (1 released, -1 pressed)
Cluth pedal: Axis 1 (1 released, -1 pressed)
DPAD left/right: Axis 4 (-1 left, 1 right)
DPAD up/down: Axis 5 (-1 up, 1 down)
Button X: B0
Button Square: B1
Button Circle: B2
Button Triangle: B3
Right paddle shifter: B4
Left paddle shifter: B5
R2: B6
L2: B7
Share: B8
Option: B9
Button Intro (inside red knob): B10
R3: B10
L3: B11
Shifter 1st gear: B12
Shifter 2nd gear: B13
Shifter 3rd gear: B14
Shifter 4th gear: B15
Shifter 5th gear: B16
Shifter 6th gear: B17
Red knob right: B18
Red knob left: B19
Button "+": B20
Button "-": B21
Shifter reverse gear: B22
```

Other emulation modes are seldom used.

**Comment by KernelZechs** [comment] 2019-12-18 15:37
@berarma that is super useful, thank you.

@leillo1975 I think I have what I need, but a screen recording using OBS wouldn't hurt to have for reference. 

I'll look into getting a beta build done with a wheel theme.

**Comment by leillo1975** [comment] 2019-12-18 20:00
Here is your g29 video:
https://youtu.be/3r4ySaGpeDs
Axis0 is wheel, Axis2 gas pedal, Axis3 brake, Axis1 is clutch, Axis 4 and 5 digital dpad

**Comment by KernelZechs** [comment] 2019-12-18 21:12
@leillo1975 @berarma 

Below is an attached video of a demo wheel theme showing off a working wheel a pedals, gearbox buttons. The axis controls were emulated using a Xbox One controller analog stick.

https://www.youtube.com/watch?v=9gO2b8NBdoA&feature=youtu.be

If this looks good to you, I can send you a beta build to test this feature out on your actual racing wheels. If it works to your satisfaction, I'll develop some real themes and do a new release hopefully by the end of the weekend.

**Comment by leillo1975** [comment] 2019-12-18 21:25
Of course is good, and of course I would like to test it. Thanks a lot

**Comment by berarma** [comment] 2019-12-18 21:28
The mapping of the axis is right. The gear buttons is not, it's B12-B18.

The gears are not really that important since they're normally displayed in the games' HUD. And neither most other buttons since they don't have standard functions. But, would it be possible to add the clutch pedal?

I think the main inputs would be the wheel, gas, brake and clutch. I'd like to hear @leillo1975 oppinion on this.

Even if you can't do them all it would be a really cool tool. Thanks @KernelZechs.

**Comment by KernelZechs** [comment] 2019-12-18 21:28
@berarma those are mapped to my Xbox controller, you can map them to any button you wish using the mapping table.

**Comment by KernelZechs** [comment] 2019-12-18 21:30
Also adding a clutch pedal is as easy as adding the rest of them, mostly the only new feature here is the wheel functionality that didn't exist before. Now that I can have that I can build pedal / wheel / gearbox themes for racing wheels. @berarma 

(Sorry I didn't mean to not finish my last ticket)

**Comment by berarma** [comment] 2019-12-18 21:33
OK. I didn't know it could be mapped by the user. It sounds good.

**Comment by KernelZechs** [comment] 2019-12-18 21:42
https://ojdproject.com/downloads/linux/unstable/open-joystick-display-2.7-beta1-x64-linux.tar.gz
@leillo1975 @berarma 

Instructions:
I suggest creating a new profile to get started.

- Select Racing Wheel Theme
- Create a New Profile Mapping
- Gearbox Buttons:
  - Create 7 Buttons, Use the new GEAR-# for each one and REVERSE, assign it to the button you want to use (for your Logitech should be Button 12-18)
- Triggers
  - Trigger ID 0 (Wheel): Axis 0, Default Values
  - Trigger ID 1 (Acceleration) Axis 2, Default Values
  - Trigger ID 2 (Brake) Axis 3, Default Values
  - NOTE: You may not see actuation like you see in my video, totally up to the way the pedal is developed.

Give this a try and let me know how it works out.

**Comment by leillo1975** [comment] 2019-12-18 22:59
I have the same problem that https://github.com/KernelZechs/open-joystick-display/issues/27#issue-539875098. I can't open the app using the executable file. If I use a terminal I don't see any control on it:
 
![Captura de pantalla de 2019-12-18 23-58-24](https://user-images.githubusercontent.com/551821/71130521-5c25ba00-21f2-11ea-90ce-8d7aa1d66ded.png)

**Comment by KernelZechs** [comment] 2019-12-18 23:34
*sigh* frustrating. Not your fault though, it should just work regardless but electron is being a pain. I'm out at the moment but when I get back I will compile a new binary in Debian which should resolve the problem. Sorry for the headache :(

-------- Original Message --------

**Comment by leillo1975** [comment] 2019-12-18 23:38
Don't worry about it. Now I'm going to sleep, and until 20:30 CET of tomorrow I won't be able to prove it, because I'll be away from home all day.

**Comment by KernelZechs** [comment] 2019-12-19 03:44
@leillo1975 Here is a rebuild OJD, let me know if this works for you:
https://ojdproject.com/downloads/linux/unstable/open-joystick-display-2.7-beta1-debian-x64-linux.tar.gz

In the meantime I'll start working on some real themes for the application.

**Comment by leillo1975** [comment] 2019-12-19 09:49
> @leillo1975 Here is a rebuild OJD, let me know if this works for you:
> https://ojdproject.com/downloads/linux/unstable/open-joystick-display-2.7-beta1-debian-x64-linux.tar.gz
> 
> In the meantime I'll start working on some real themes for the application.

I will try it this night on my home PC. I tried both on my work's computer and they run correctly. In my house I use Ubuntu 18.04.3, and in my work 19.10. Perhaps 19.10 uses some dependencies more advanced that 18.04 necessary to run your software

**Comment by berarma** [comment] 2019-12-19 15:31
It's working on Debian 10.

**Comment by KernelZechs** [comment] 2019-12-19 17:00
@berarma @leillo1975 

https://www.youtube.com/watch?v=z51LPAYWREU&feature=youtu.be

Here is a video of my work last night on a G29 wheel, pedal, and gearbox set. Please let me know what you all think. For this feature to be complete I will have the following configurations:

- G29 (PC/PS4) with/without gearbox
- G29 (PC/PS4) Gearbox Right/Left hand side
- G209 (PC/Xbox) with/without gearbox
- G209 (PC/Xbox)  Gearbox Right/Left hand side.

Even if you don't have a Logitech wheel or another brand of logitech wheel this should be generic enough to use with everything.

**Comment by leillo1975** [comment] 2019-12-19 20:09
It works great with

> @leillo1975 Here is a rebuild OJD, let me know if this works for you:
> https://ojdproject.com/downloads/linux/unstable/open-joystick-display-2.7-beta1-debian-x64-linux.tar.gz
> 
> In the meantime I'll start working on some real themes for the application.

Now it works on Ubuntu 18.04. Thanks a lot. I created a profile and I configured the triggers for direcrtion, brake and throttle, and it works!
I found two problems. The first one is that pedals are inverted and when you accelerate or brake, in the screen you see the opposite. There is an option to invert triggers?
The second one is a problem with the degrees/range  of the wheel. Each game/car can use a different range . I see in your app that this range is like 300º. I think you must create a field on the direction trigger to configure the degrees of the wheel. Before, I had the steering wheel configured for 900º (default) and I had to turn it several times to see on screen how it turned only about 150º. The ideal would be to see the same turns on the screen.

**Comment by KernelZechs** [comment] 2019-12-19 20:12
@leillo1975 
```
I found two problems. The first one is that pedals are inverted and when you accelerate or brake, in the screen you see the opposite. There is an option to invert triggers?
```
I believe that they are correct but the visualization is weird, I'm going to do a new build this evening with the themes I made so let me know if they are inverted there. If they are, yes I can invert them.

```
The second one is a problem with the degrees/range of the wheel. Each game/car can use a different range . I see in your app that this range is like 300º. I think you must create a field on the direction trigger to configure the degrees of the wheel. Before, I had the steering wheel configured for 900º (default) and I had to turn it several times to see on screen how it turned only about 150º. The ideal would be to see the same turns on the screen.
```
Because I don't have one to test this was a concern of mine BUT I can solve this by adding a new degree field to let you choose how many degrees you wish for the wheel to turn from center.

**Comment by leillo1975** [comment] 2019-12-19 20:34
> I believe that they are correct but the visualization is weird, I'm going to do a new build this evening with the themes I made so let me know if they are inverted there. If they are, yes I can invert them.

I think if you put a checkbox to invert the trigger it could be perfect

> Because I don't have one to test this was a concern of mine BUT I can solve this by adding a new degree field to let you choose how many degrees you wish for the wheel to turn from center.
**Perfect**. We can create some profiles with different ranges (G29_360, G29_450, G29_900 ....)

**Comment by leillo1975** [comment] 2019-12-19 23:04
Your work is Incredible, awesome.... 
invert checkbox and degrees field work great!. And the theme is looks perfect. ...
Now we go with the problems. I found that the degrees don't work as expected (don't worry, is not important). If you put 450º, the wheel acts like 900º, if you put 180º, like 360. I think that yu only have to divide the effect of the degrees by 2 to work fine.

Then... Axis2 is for accelerate, and axis1 for clutch. You put Axis 2 for clutch and Axis1 for accelerate.

As you can see it's just a couple of trifles, but the rest of the wheel profile is amazing

**Comment by KernelZechs** [comment] 2019-12-19 23:08
@leillo1975 
The reason for the degrees is that I don't want to make assumptions about the calculations for other racing wheel specs, so it just does the raw degrees- as you figured out dividing it by half worked for you, for others it may not be the case.

The reason for the axis is actually quite simple, triggers in themes are done top to bottom, left to right, so:
Wheel (Trigger ID:0), Clutch (Trigger ID:1), Brake (Trigger ID:2), Accel (Trigger ID:3). Since you can change the axis on any of these triggers, the order is dynamic, again- this is to ensure optimal support across various devices and not just the Logitech devices.

You can see that logic in this PR: https://github.com/KernelZechs/open-joystick-display/blob/9e3638615a274c760c4b676cc34071d324927760/app/themes/ojd-racing-wheels/g29/theme-g29.html

Let me know if this makes sense.

**Comment by KernelZechs** [comment] 2019-12-19 23:13
To follow up, for your configuration:
Trigger 0 (Wheel) : Axis 0,
Trigger 1 (Clutch): Axis 1
Trigger 2 (Brake): Axis 3
Trigger 3 (Accel): Axis 2

**Comment by leillo1975** [comment] 2019-12-19 23:18
> @leillo1975
> The reason for the degrees is that I don't want to make assumptions about the calculations for other racing wheel specs, so it just does the raw degrees- as you figured out dividing it by half worked for you, for others it may not be the case.

The range in degrees in the Steering Wheels is counted from end to end, not from center to end.

**Comment by KernelZechs** [comment] 2019-12-19 23:20
@leillo1975 Alright, I'll trust you and make the change, but if someone complains you're getting tagged on it lol.

**Comment by KernelZechs** [comment] 2019-12-19 23:28
@leillo1975 

![image](https://user-images.githubusercontent.com/46404303/71217876-4e714280-228d-11ea-8425-99363d92d219.png)

https://ojdproject.com/downloads/linux/unstable/open-joystick-display-2.7-beta3-x64-linux.tar.gz

I also made a note on the label that it is divided.

**Comment by leillo1975** [comment] 2019-12-19 23:44
You are so quick! I will try it before going to sleep
Take a look to this test with Speed Dreams:
https://youtu.be/RqqZpD03oIA

**Comment by leillo1975** [comment] 2019-12-19 23:50
Now everything works perfect. Thanks a lot for all of your work. I will use this g29 profile in all of my youtube racing videos

**Comment by KernelZechs** [comment] 2019-12-19 23:50
@leillo1975 
AWESOME! Looks great! 

I'm not sure if it was intentional but the pedal axis' look inverted, because when you decelerated the pedals were down but not up, but either way it looks to be functioning as intended!

@berarma do you have any feedback before I cut a release?

**Comment by leillo1975** [comment] 2019-12-19 23:56
> @leillo1975
> AWESOME! Looks great!
> 
> I'm not sure if it was intentional but the pedal axis' look inverted, because when you decelerated the pedals were down but not up, but either way it looks to be functioning as intended!

You are right, I forgot to invert it. Cheers!

**Comment by berarma** [comment] 2019-12-19 23:57
> @berarma do you have any feedback before I cut a release?

Awesome!

> @leillo1975 Alright, I'll trust you and make the change, but if someone complains you're getting tagged on it lol.

Don't worry, it's correct. Some racing games have a setting for the wheel range and they do it like this too. It's universal for all brands and software.

**Comment by KernelZechs** [comment] 2019-12-19 23:59
Cool, then I will cut a release and post it here. Once that is done I will close out this ticket as complete. Thank you both for all of your hard work testing this, I couldn't have completed this feature without you all.

**Comment by KernelZechs** [comment] 2019-12-20 00:35
OJD 2.7 has been released to the public, the binary is on the website. I'm going to close out this ticket now. Just a note, as a thanks for helping me out I added your names and github link to the about dialog, you should be able to see it in the most recent build.

Thanks again, have a great holiday!

**Closed by KernelZechs** 2019-12-20 00:35 UTC
Labels: enhancement

**Comment by leillo1975** [comment] 2019-12-23 09:50
@KernelZechs , dedicated to you:
https://youtu.be/QZcewtPKGEw
https://youtu.be/deJ5haHlovc
Thanks again!
